// Regenerates src/adapter-abi.ts from the Foundry build. Run `forge build` in ../evm first.
import { readFileSync, writeFileSync } from "node:fs";

const artifact = new URL("../../evm/out/EoxAssertionAdapter.sol/EoxAssertionAdapter.json", import.meta.url);
const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
const out = new URL("../src/adapter-abi.ts", import.meta.url);
writeFileSync(
  out,
  `// Generated by scripts/gen-abi.mjs from the Foundry build of EoxAssertionAdapter. Do not edit.\n` +
    `export const adapterAbi = ${JSON.stringify(abi, null, 2)} as const;\n`,
);
console.log(`wrote ${abi.length} ABI entries`);
