skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
eox_oracle = "GFZe6fv5iVwJ772JKVhYMWP4mMgHBzoCdcR2Z5QY5DCf"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
