// Generated by scripts/gen-abi.mjs from the Foundry build of EoxAssertionAdapter. Do not edit.
export const adapterAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "oracle_",
        "type": "address",
        "internalType": "contract IOptimisticOracleV3"
      },
      {
        "name": "wormhole_",
        "type": "address",
        "internalType": "contract IWormhole"
      },
      {
        "name": "bondCurrency_",
        "type": "address",
        "internalType": "contract IERC20"
      },
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ASSERTION_WINDOW",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "CONSISTENCY_FINALIZED",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "LIVENESS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "PAYLOAD_MAGIC",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "PAYLOAD_VERSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "assertResult",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "claim",
        "type": "tuple",
        "internalType": "struct EoxAssertionAdapter.Claim",
        "components": [
          {
            "name": "evidenceRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "methodologyImageId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "outputHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "resolutionUriHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "resolutionUri",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "assertionId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "assertionDisputedCallback",
    "inputs": [
      {
        "name": "assertionId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "assertionResolvedCallback",
    "inputs": [
      {
        "name": "assertionId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "assertedTruthfully",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "bondCurrency",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IERC20"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "claimText",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "claim",
        "type": "tuple",
        "internalType": "struct EoxAssertionAdapter.Claim",
        "components": [
          {
            "name": "evidenceRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "methodologyImageId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "outputHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "resolutionUriHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "resolutionUri",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "cutoffTimestamp",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "epochs",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct EoxAssertionAdapter.Epoch",
        "components": [
          {
            "name": "opened",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "settled",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "methodologyImageId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "bond",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "activeAssertion",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "resultAssertion",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "result",
            "type": "tuple",
            "internalType": "struct EoxAssertionAdapter.Claim",
            "components": [
              {
                "name": "evidenceRoot",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "methodologyImageId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "outputHash",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "resolutionUriHash",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "identifier",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "openEpoch",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "methodologyImageId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "bond",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "oracle",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IOptimisticOracleV3"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "publishResult",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "sequence",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "resultPayload",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "wormhole",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IWormhole"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "AssertionDisputed",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "indexed": true,
        "internalType": "uint16"
      },
      {
        "name": "assertionId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AssertionRejected",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "indexed": true,
        "internalType": "uint16"
      },
      {
        "name": "assertionId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EpochOpened",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "indexed": true,
        "internalType": "uint16"
      },
      {
        "name": "methodologyImageId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "bond",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EpochSettled",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "indexed": true,
        "internalType": "uint16"
      },
      {
        "name": "assertionId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "result",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct EoxAssertionAdapter.Claim",
        "components": [
          {
            "name": "evidenceRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "methodologyImageId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "outputHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "resolutionUriHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ResultAsserted",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "indexed": true,
        "internalType": "uint16"
      },
      {
        "name": "assertionId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "asserter",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "claim",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct EoxAssertionAdapter.Claim",
        "components": [
          {
            "name": "evidenceRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "methodologyImageId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "outputHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "resolutionUriHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ResultPublished",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "indexed": true,
        "internalType": "uint16"
      },
      {
        "name": "sequence",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AssertionPending",
    "inputs": [
      {
        "name": "assertionId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "AssertionWindowClosed",
    "inputs": [
      {
        "name": "closedAt",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "BondBelowMinimum",
    "inputs": [
      {
        "name": "bond",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minimum",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "EpochAlreadyOpen",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      }
    ]
  },
  {
    "type": "error",
    "name": "EpochAlreadySettled",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      }
    ]
  },
  {
    "type": "error",
    "name": "EpochNotOpen",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      }
    ]
  },
  {
    "type": "error",
    "name": "EpochNotSettled",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotOracle",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ResolutionUriMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "StringsInsufficientHexLength",
    "inputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "length",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TooEarly",
    "inputs": [
      {
        "name": "cutoff",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownAssertion",
    "inputs": [
      {
        "name": "assertionId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "WrongFee",
    "inputs": [
      {
        "name": "expected",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "given",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "WrongMethodology",
    "inputs": [
      {
        "name": "expected",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "given",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  }
] as const;
